#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D ssaoRaw;
layout(set = 0, binding = 1, r8) uniform writeonly image2D outSSAOBlur;

void main() {
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imgSize = textureSize(ssaoRaw, 0);
    
    if (texCoord.x >= imgSize.x || texCoord.y >= imgSize.y)
        return;

    vec2 texelSize = 1.0 / vec2(imgSize);
    float result = 0.0;
    
    // 4x4 blur to match the 4x4 noise
    for (int x = -2; x < 2; ++x) 
    {
        for (int y = -2; y < 2; ++y) 
        {
            vec2 offset = vec2(float(x), float(y)) * texelSize;
            vec2 uv = (vec2(texCoord) + 0.5) * texelSize + offset;
            result += texture(ssaoRaw, uv).r;
        }
    }
    
    result = result / (4.0 * 4.0);
    
    imageStore(outSSAOBlur, texCoord, vec4(result));
}
